application: aefinance
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css
  
- url: /static/js
  static_dir: static/js

- url: /signin
  script: main.application
  login: required

- url: /profile
  script: main.application
  login: required

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest